In [17]:
import torch

In [18]:
w_1 = torch.tensor([0.23], requires_grad=True)
b_1 = torch.tensor([0.1], requires_grad=True)

# Inputs
x_1 = torch.tensor([1.23])
y = torch.tensor([1.])

In [19]:
u = w_1 * x_1
z = u + b_1
print(z)
a = torch.sigmoid(z)
print(a)

tensor([0.3829], grad_fn=<AddBackward0>)
tensor([0.5946], grad_fn=<SigmoidBackward0>)


In [20]:
import torch.nn.functional as F

l = F.binary_cross_entropy(a, y)

# best proctice to use

l = F.binary_cross_entropy_with_logits(z, y)
print(l)

tensor(0.5199, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [21]:
import math

math.log(0.5946)

-0.5198663684181397

In [13]:
# from torch.autograd import grad
# grad_l_w1 = grad(l, w_1, retain_graph=True)
# print(grad_l_w1)

(tensor([-0.4987]),)


In [16]:
# grad_l_b = grad(l, b_1, retain_graph=True)
# print(grad_l_b)

(tensor([-0.4054]),)


In [22]:
l.backward()

In [25]:
w_1.grad, b_1.grad

(tensor([-0.4987]), tensor([-0.4054]))

In [27]:
# Suppose you have the following function:
# f(x, y, z) = 4x^3 + 3y^2 + 2z.
# What is the partial derivative of f with respect to y when x=3, y=2, z=5?


import torch
from torch.autograd import grad

x = torch.tensor([3.])
y = torch.tensor([2.], requires_grad=True)
z = torch.tensor([5.])

f = 4 * x ** 3 + 3 * y ** 2 + 2 * z

grad_f_y = grad(f, y, )
print(grad_f_y)


(tensor([12.]),)


# using nn.linear

In [28]:
import torch

torch.manual_seed(123)
linear = torch.nn.Linear(in_features=2, out_features=1)
linear.weight, linear.bias

(Parameter containing:
 tensor([[-0.2883,  0.0234]], requires_grad=True),
 Parameter containing:
 tensor([-0.3512], requires_grad=True))

In [29]:
x = torch.tensor([1.2, 0.5])
print(x)

tensor([1.2000, 0.5000])


In [30]:
w = linear.weight.detach()
b = linear.bias.detach()
z = x.matmul(w.T) + b

print(z)

tensor([-0.6855])


In [32]:
# type simpler
import torch

torch.manual_seed(123)
linear = torch.nn.Linear(in_features=2, out_features=1)
print(linear.weight)
print(linear.bias)

x = torch.tensor(
    [1.2, 0.5]
)
z = linear(x)
print(z)

Parameter containing:
tensor([[-0.2883,  0.0234]], requires_grad=True)
Parameter containing:
tensor([-0.3512], requires_grad=True)
tensor([-0.6855], grad_fn=<ViewBackward0>)


In [35]:
# type simpler
import torch

torch.manual_seed(123)
linear = torch.nn.Linear(in_features=2, out_features=1)
print(linear.weight)
print(linear.bias)

x = torch.tensor(
    [
        [1.2, 0.5],
        [0.7, 0.8],
        [0.1, 0.2]
    ]
)
z = linear(x)
print(z)

Parameter containing:
tensor([[-0.2883,  0.0234]], requires_grad=True)
Parameter containing:
tensor([-0.3512], requires_grad=True)
tensor([[-0.6855],
        [-0.5343],
        [-0.3753]], grad_fn=<AddmmBackward0>)


In [38]:
list(torch.nn.Linear(in_features=5, out_features=1).parameters())

[Parameter containing:
 tensor([[-0.0879, -0.3412,  0.2928, -0.1055,  0.1436]], requires_grad=True),
 Parameter containing:
 tensor([0.3162], requires_grad=True)]