In [73]:
import torch
torch.manual_seed(123);

In [74]:
torch.manual_seed(123)
idx = torch.tensor([2,3,1]) # 3 Training examples, where each index corresponds to the character

number_idx = max(idx)+1  # input dimension of a one-hot encoded vector is the number of indices (the highest index +1)
output_dim = 5

embedd = torch.nn.Embedding(number_idx, output_dim)
print(embedd(idx))

tensor([[ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953],
        [ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015]],
       grad_fn=<EmbeddingBackward0>)


In [81]:
embedd.weight.T.detach()

tensor([[ 0.3374,  1.3010,  0.6957, -2.8400],
        [-0.1778,  1.2753, -1.8061, -0.7849],
        [-0.3035, -0.2010, -1.1589, -1.4096],
        [-0.5880, -0.1606,  0.3255, -0.4076],
        [ 1.5810, -0.4015, -0.6315,  0.7953]])

In [82]:
linear.weight.detach()

tensor([[ 0.3374,  1.3010,  0.6957, -2.8400],
        [-0.1778,  1.2753, -1.8061, -0.7849],
        [-0.3035, -0.2010, -1.1589, -1.4096],
        [-0.5880, -0.1606,  0.3255, -0.4076],
        [ 1.5810, -0.4015, -0.6315,  0.7953]])

In [80]:
# using torch.nn.Linear

torch.manual_seed(123)
idx = torch.tensor([2,3,1])
onehot = torch.nn.functional.one_hot(idx)
linear = torch.nn.Linear(number_idx, output_dim, bias=False)
print(onehot)
linear.weight = torch.nn.Parameter(embedd.weight.T.detach())
print(linear(onehot.float()))

tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])
tensor([[ 0.6957, -1.8061, -1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096, -0.4076,  0.7953],
        [ 1.3010,  1.2753, -0.2010, -0.1606, -0.4015]], grad_fn=<MmBackward0>)


In [76]:
print(linear(onehot.float()))

tensor([[-0.2483, -0.3634, -0.1847, -0.1836, -0.1179],
        [ 0.1886, -0.3975,  0.1871, -0.0983,  0.1605],
        [ 0.0166,  0.3665,  0.2264, -0.3034,  0.3274]], grad_fn=<MmBackward0>)


In [77]:
import re

In [78]:
tt = "this is a test to tokenize dont's"

def tokenize(text):
    return [r.lower() for r in re.findall("\w+", text)]

tokenize(tt)

['this', 'is', 'a', 'test', 'to', 'tokenize', 'dont', 's']